name: Build Automation

on:
  push:
    branches:
      - main
    tags:
      - 'v1.0.11' # Triggers the workflow on version tags like v1.0.0

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Code formatter
        run: dart format --output=none --set-exit-if-changed .

      - name: Run Dart analyzer
        run: flutter analyze --fatal-warnings

      - name: Run tests
        run: flutter test

  build_apk:
    runs-on: ubuntu-latest
    needs: analyze_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

  upload_release:
    runs-on: ubuntu-latest
    needs: build_apk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/*
          tag: ${{ github.ref }}
          token: ${{ secrets.TOKEN }}
          name: Release ${{ github.ref_name }}
          body: |
            APK for version ${{ github.ref_name }} is ready.